language: swift
os: osx
git:
  depth: 1
cache:
  directories:
  - /usr/local/Homebrew
  - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
jobs:
  include:
    - stage: Test go packages
      osx_image: xcode10
      before_install: brew update
      install:  brew list --versions go | grep "1\.11.*" || brew upgrade go@1.11
      script: make test-go

    - stage: Test relax commands
      osx_image: xcode8
      script: test/travis_ci.sh

    - stage: Test relax commands
      osx_image: xcode8.3
      script: test/travis_ci.sh

    - stage: Test relax commands
      osx_image: xcode9.4
      script: test/travis_ci.sh

    - stage: Test relax commands
      osx_image: xcode10
      script: test/travis_ci.sh

env:
  global:
  - secure: YPL0eJ1L8/1Etjvc+kjvOg7+FBF9WXajPpVblrIsH8KvNh8HRFmh1xIqQBFHGLu7QFzek/ih+LlKmVGG4NcHMcJLZ9+/IjoQhMfo9FsWWOlc7jRDTNA6pIL0ISRxJatVauvLGlrOegTwitpQmpGr2naHgtytBtLZ0CyFa1zcorc0mo8qfIdk+fFxauhAKfe0QrXeBgHXi0YjyISS1arcyeri1rBOvBEluu5IaLGqtYCNqmIPVKnhPrY0OD5xl69RxfuJ8RLuBgcTeFKLBIQl7GH9NofrtZ2uuoJTrcbMLMxZhTwPcOnG0jRnFzmkPwodA1zc6HDhvIrDTBKFwNEkU+hTDuExaX2uQJa+5yfrljIvTHMuX91K6L+dfkaC33ModmIyNnfDOUk2Q3vcNJUZ1OwwQj0TVrkhJScuLGki2IdbApfcVkBrZnTxc/CgopjN6Ett37iYoFB/kTcKIy4NyhA9FmlvQZnIw71/s9lVy9bYdlVpyXVkWVR3Md9/5lnGiKkXSUuy38FxRSrdOMnhUpTWI8UXy0/6I7/su8vIMAgEaZw6Cr1LVXQKQaaYWj97bUnhJ+hHdboI/Df2HGY178ZWXEWHsgW+WvowtEDwU2CS6V9wic6tWZ5XUNlgwiTupo3qpQXFxJkyx8vHNQwNVNZYt8pgi/M1u+isZkhqADw=
  - secure: XwdnJfgrOZg9YEZhtORLcZjFzczqviEiJr6CbaDM7khcUzKw6FMQh7dHxGdCK68S51u5P9lqsb4pvLRjDMe9oK57BH0RKQPyjbnALH+gyO0pFuDAcKBn9L7PeW78S3BqmuQ1XGo8ZR+hyKSokeEIO5w60dyERDNfg/W/aE9EM6ZD0SWjNwJnV6aWEF21zY3JbRzxGr1IlEHcbLHz4zkcGWO+LnRqCGQg79Xv90KajKrTpEgGt4nHgMOmI9OBX8IV+17+iqhj8+p5ujaaF/SIibYPPoQSEOChXTwuLKcWeRV2cXtKqanlsm4tIhaH1UTODSwMb4bBZUFhHl77CDlnDmq7hHcFu/7cQjC4PpNCyITy+SPiWnp5GHfIgGwXdvPrg83jeoGIhMi5nZ5d+nsjc+gnrKYpgfsZcIien65K0E0bOoihwDnXzEqAUQSiOVJxBvvWJUAnkg/Ku80afl8kfPUqCB2ZfDkOoPi5M2xSgsxyxrVgJIpO4EDsI2rZFptvPklCXpIhETtfxi5HwydHB95QnEeEgTIg58Zm/LDODq+U8MOo/1Y7fGQIMStg0T77uOkz8+0wOc3V3xUU9352BRBlYHOjv3bc+JkMvLpHxyRHoWe9D5mRJ1LJGUoAYEqyP4MpCQ9Hr7cYcwDNCxIfZz/uuBDRrV2TPnE9hR9ph/M=
